### ISSUE TITLE
could not train using python3.5 and tf 0.11 

### ISSUE THREAD

**Issue by jhave** [paarthneekhara/byteNet-tensorflow#2]
encountered 2 few errors.
perhaps due to version incompatibility.

$ python train_p3.py --data_dir=/Users/jhave/Desktop/github/byteNet-tensorflow/Data/pf 
Traceback (most recent call last):
  File "train_p3.py", line 6, in <module>
    from ByteNet import model
  File "/Users/jhave/Desktop/github/byteNet-tensorflow/ByteNet/model.py", line 2, in <module>
    import ops
**ImportError: No module named 'ops'**

-----
after ImportError I moved ops.py into same folder as train, then encountered...
-----

$ python train_p3.py --data_dir=/Users/jhave/Desktop/github/byteNet-tensorflow/Data/pf 
Traceback (most recent call last):
  File "train_p3.py", line 85, in <module>
    main()
  File "train_p3.py", line 42, in main
    bn_tensors = byte_net.build_prediction_model()
  File "/Users/jhave/Desktop/github/byteNet-tensorflow/ByteNet/model.py", line 48, in build_prediction_model
    decoder_output = self.decoder(source_embedding)
  File "/Users/jhave/Desktop/github/byteNet-tensorflow/ByteNet/model.py", line 123, in decoder
    layer_output = self.decode_layer(curr_input, dilation, layer_no)
  File "/Users/jhave/Desktop/github/byteNet-tensorflow/ByteNet/model.py", line 111, in decode_layer
    name = "dec_dilated_conv_laye{}".format(layer_no)
  File "/Users/jhave/Desktop/github/byteNet-tensorflow/ops.py", line 50, in dilated_conv1d
    restored = batch_to_time(conv, dilation)
  File "/Users/jhave/Desktop/github/byteNet-tensorflow/ops.py", line 21, in batch_to_time
    [(shape[0]/dilation), -1, shape[2]])
  File "//anaconda/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1977, in reshape
    name=name)
  File "//anaconda/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 573, in apply_op
    _Attr(op_def, input_arg.type_attr))
  File "//anaconda/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
**TypeError: DataType float32 for attr 'Tshape' not in list of allowed values: int32, int64**

**Comment by paarthneekhara** [comment]
Please use python 2.7. tf > 0.10 should work. I'll update the requirements in the readme.

**Comment by jhave** [comment]
thanks. that worked.
